---
title: "Model Inspection - Regression"
author: "JW"
date: "`r Sys.Date()`"
output: html_document
runtime: shiny
---

```{css, echo=FALSE}
.main-container {
  max-width: 100% !important;
  margin-left:  0 !important;
  margin-right: 0 !important;
  padding-left:  15px;
  padding-right: 15px;
}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
output_dir <- here::here("output")
devtools::load_all(here::here("../packages/damageRF"))
```

## Modell - Auswahl

```{r selectors}
run_dirs <- list.dirs(output_dir, full.names = FALSE, recursive = FALSE) |>
  (\(x) x[startsWith(x, "run")])()

select_run = shiny::selectInput("run", "Run", choices = run_dirs)

select_bspid = shiny::renderUI({
  shiny::req(input$run)
  model_dirs <- list.dirs(
    file.path(output_dir, input$run),
    full.names = FALSE,
    recursive = FALSE
  )
  shiny::selectInput("model", "BSPID", choices = model_dirs)
})

select_rds = shiny::renderUI({
  shiny::req(input$run, input$model)
  rds_files <- list.files(
    file.path(output_dir, input$run, input$model),
    pattern = "\\.rds$", ignore.case = TRUE
  )
  shiny::selectInput("rds_file", "Model", choices = setNames(rds_files, basename(rds_files)))
})

button_read = shiny::actionButton("load", "Einlesen", icon = shiny::icon("folder-open"))

shiny::fluidRow(
  shiny::column(3, select_run),
  shiny::column(3, select_bspid),
  shiny::column(3, select_rds),
  shiny::column(3, shiny::div(style = "margin-top: 25px;", button_read))
)
```

## Ergebnisse

```{r load_rds}
rds_data <- shiny::eventReactive(input$load, {
  shiny::req(input$run, input$model, input$rds_file)
  readRDS(file.path(output_dir, input$run, input$model, input$rds_file))
})
```

```{r dynamic_ui}
shiny::renderUI({
  shiny::req(rds_data())
  shiny::tagList(
    shiny::hr(),
    shiny::h4("Modellmetriken"),
    shiny::plotOutput("plot_plotter", height = "800px")
  )
})
```

```{r dynamic_renderers}
shiny::observe({
  data <- rds_data()
  shiny::req(data)

  shiny::withProgress(message = "Plotting", value = 0, {
    output[["plot_plotter"]] <- shiny::renderPlot({
      damageRF::plotter(data)
    })
    shiny::incProgress(amount = 1, detail = "Metriken")
  })
})
```
