---
title: "Datainsight"
author: "JW"
date: "`r Sys.Date()`"
output: html_document
---

## **Setup**

Zu Beginn: Setze das Arbeitsverzeichnis auf das Verzeichnis dieses Scriptes, um relative Pfade verwenden zu können.

#### Imports

```{r packages, warning=FALSE, message=FALSE}
library(RSQLite)
library(ggplot2)
library(dplyr)
library(tidyr)
library(rpart)
library(caret)   
library(rpart.plot)
library(vip)
library(pdp)
library(doParallel)
library(foreach)
library(ipred)
library(ranger)
```


## *Setup*


#### Hilfsfunktionen

```{r helpers, warning=FALSE}
source("helpers.R")
```

#### Database connection

```{r database}
db <- RSQLite::dbConnect(RSQLite::SQLite(), "data/db/prepdata.db")
```

#### Seeding
```{r seeding}
set.seed(1234)
```

## *Models*

```{r prepatarion}
# Read prepared data and factorise the character columns
readin = DBI::dbReadTable(db, "prepdata")

bspids = unique(readin$bsp_id)
bspid = bspids[1]

# Prepare data
prep = readin |> 
  # Filter for bspid of interest
  dplyr::filter(bsp_id == bspid) |> 
  # Factorise
  dplyr::mutate(across(all_of(names(readin)[sapply(readin, is.character)]), as.factor)) |>
  dplyr::mutate(across(where(is.factor), ~ factor(., levels = levels(.))))
```

```{r splitting}
# Train split
train = prep |> 
  dplyr::filter(
    schaden %in% sample(unique(schaden), size = 0.8 * length(unique(schaden)))
  )

# Test split
test = setdiff(prep, train)

# Check split proportion
nrow(train) / (nrow(train) + nrow(test))

# Check level equality
all.equal(levels(train), levels(test))
```

#### Model formula

```{r formula}
# Available predictorvariables
predictors = c(
  "baujahr", "prufjahr", "bauwerksart_text", "stadium_text", "konstruktion", 
  "laenge", "breite", "flaeche", "statisches_system_laengs", 
  "statisches_system_quer", "hoechst_sachverhalt_oben", 
  "hoechst_sachverhalt_unten", "jast_lage", "br_bauwerkswinkel", 
  "br_bw_winkel_richtung", "laengenklasse", "baustoffklasse", 
  "br_maximale_laengsneigung", "lage_bl", "bauteil", 
  "bautlgrupp", "konteil", "zwgruppe", "menge_all", 
  "menge_di_m", "pra", "alter"
) # Entfernt: "menge_di"

# Just paste all predictors
fml_all <- as.formula(
  paste("bewert_d", "~", paste(predictors, collapse = " + "))
)
```

#### One stupid Decision Tree

```{r decisiontree}
# Grow decision tree
dt = rpart::rpart(
  formula = fml_all,
  data = train,
  method  = "anova",
  # Controll parameter cp: Pruning complexity parameter, 
  # xval: Number of crossvalidations, 
  # control = list(cp = 0, xval = 10)
)
  
# Display decision tree
rpart.plot::rpart.plot(dt, box.palette = "BuGn")

# Variable importance
vip::vip(dt)

# Crossvalidation error over tree size
dt$cptable
plotcp(dt)
```
