## Base image
FROM rocker/r-ver:latest
# FROM rocker/tidyverse:4.3.2

## Install system dependencies
RUN apt-get update && apt-get install -y \
   libcurl4-openssl-dev \
   libssl-dev \
   libxml2-dev \
   git \
   build-essential \
   pandoc \
   ghostscript \
   && rm -rf /var/lib/apt/lists/*

# Install R packages
# RUN R -e "install.packages('renv')"

## Set working directory
WORKDIR /app

## Copy project files into the image
COPY . /app

# Restore the environment
# RUN R -e "renv::restore()"

## install renv
RUN Rscript -e 'install.packages(c("renv"))'

## set the renv path var to the renv lib
ENV RENV_PATHS_LIBRARY renv/library

## restore packages from renv.lock
RUN Rscript -e 'renv::restore(lockfile="/app/renv.lock")'

## Default command to run when the container starts
CMD ["Rscript", "-e", "rmarkdown::render('run_rf2.Rmd')"]